# Setup
title: "Je'aime Powell"
description: A portfolio of various projects and experiences. 
url: https://jeaimehp.github.io/not-pure-poole-test
avatar: /Jeaime-Meh.jpeg
paginate: 5
permalink: pretty
cover_image: /IMG_1182-Large.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: jeaimehp
  card: summary
logo: logo.png
social:
  name: Jeaime Powell
  links:
    - https://twitter.com/jeaimehp
    - https://github.com/jeaimehp
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Jeaime Powell
  url: https://github.com/jeaimehp
  email: jeaimehp@gmail.com
